### ISSUE TITLE
Clarification on configuration / settings

### ISSUE THREAD

**Issue by Incognify** [gbxyz/centralnic-registry-whmcs-plugin#1]
Hello,

New CentralNIC Registrar here. Long time user of WHMCS. 

Unfortunately I can't seem to find the documentation related to the CentralNIC API anywhere on their website, only statements to request it if desired, so am waiting on that. In the mean time, what I -have- done is whitelist our WHMCS server's IP in our CentralNIC Registrar Control's Access List and double check that the account's EPP password was correct.

Despite whitelisting the WHMCS server and confirming that the password was in fact correct, we still receive the following error:

```
An Error Occurred
Invalid configuration: Error connecting to epp.centralnic.com:700: Network is unreachable (101)
Your changes have not been saved.
```

To confirm:

"Registrar ID" as defined by the module is in fact the same CentralNIC Registrar ID used to login to the console and is as what is displayed in the CentralNIC console in the top right corner as the "Logged in as" ID, correct?

The EPP password that the module requests is what would be set at https://registrar-console.centralnic.com/settings/passwords , correct?

Is the client-certificate and private key necessary to establish a connection? I assume this would be the existing production SSL used for our WHMCS install or...?

Thank you,
-Curtis

**Comment by gbxyz** [comment]
I can't help you debug network issues, but CentralNic might. Please contact them in the first instance.

> "Registrar ID" as defined by the module is in fact the same CentralNIC Registrar ID used to login to the console and is as what is displayed in the CentralNIC console in the top right corner as the "Logged in as" ID, correct?

Your Registrar ID will be what you enter into the "Handle ID" field when you log in to the Registrar Console and will look something like `H123456789`.

> The EPP password that the module requests is what would be set at https://registrar-console.centralnic.com/settings/passwords , correct?

Yes correct.

> Is the client-certificate and private key necessary to establish a connection? I assume this would be the existing production SSL used for our WHMCS install or...?

These are optional but I would recommend them. You will have to associate the certificate with your account at https://registrar-console.centralnic.com/settings/epp_certificates.
